### ISSUE TITLE
Feature Idea: Spatial Extension of aquacrop

### ISSUE THREAD

**Issue by rbavery** [thomasdkelly/aquacrop#1]
Similar to the [original GIS extension](http://www.fao.org/aquacrop/software/aquacrop-gis/en/#c518674) the idea is to : 
* extend this package to run a high number of simulations in parallel
* define schema for spatial inputs that are easy on the user
  - this feature could also facilitate the download and preprocessing of reanalysis, remote sensing, or field measurements that spatially resolve aquacrop inputs (air temperature, soil moisture, CO2, water table level, )
* output crop yield and other results in geospatial formats (.geotiff) and/or in a format that can also store arbitrary N-d metadata, such as date (netcdf)

@kcaylor and I are curious if something like this is already on the roadmap of the original authors/maintainers of this module. The @ecohydro lab is interested in contributing to and using a feature like this and excited to build on top of this impressive implementation!

**Comment by thomasdkelly** [comment]
Hi @rbavery, a spatially-explicit framework for running the model is something I am looking at in the context of optimising irrigation management and water allocation. The ideas you have suggested sound like really interesting use cases and extensions of this. I'll send you an email to see how we can coordinate our efforts. 

Thanks, Tom

**Comment by rbavery** [comment]
Hi @thomasdkelly just checking in. I'm getting positive response from my team at Development Seed and I think I can get time to work on this. My email is ryan@developmentseed.org if you want to connect.

**Comment by thomasdkelly** [comment]
Sounds great thanks Ryan will get in touch
