### ISSUE TITLE
Custom Crop Creation

### ISSUE THREAD

**Issue by DivyaDey** [thomasdkelly/aquacrop#3]
Hi Tom,

The problem with Custom Crop creation while mentioning the Planting and Harvest Dates is not resolved yet.
Please look into the issue. Hoping for a quick fix.

Thanks
Divya Dey

![In_built_crop](https://user-images.githubusercontent.com/79834351/109472572-4d928e00-7a98-11eb-95bc-4c11598c328a.png)
![custom_crop](https://user-images.githubusercontent.com/79834351/109472615-5be0aa00-7a98-11eb-9a99-10104185890a.png)

**Comment by thomasdkelly** [comment]
Fixed in version 0.1.5 : 2nd March 2021
